// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MakeYourDiet.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230827171232_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("MakeYourDiet.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carbons")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Proteins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carbons = 1,
                            Fats = 1,
                            Name = "Product 1",
                            Proteins = 1,
                            Weight = 100
                        },
                        new
                        {
                            Id = 2,
                            Carbons = 2,
                            Fats = 2,
                            Name = "Product 2",
                            Proteins = 2,
                            Weight = 100
                        },
                        new
                        {
                            Id = 3,
                            Carbons = 3,
                            Fats = 3,
                            Name = "Product 3",
                            Proteins = 3,
                            Weight = 100
                        },
                        new
                        {
                            Id = 4,
                            Carbons = 4,
                            Fats = 4,
                            Name = "Product 4",
                            Proteins = 4,
                            Weight = 100
                        },
                        new
                        {
                            Id = 5,
                            Carbons = 5,
                            Fats = 5,
                            Name = "Product 5",
                            Proteins = 5,
                            Weight = 100
                        },
                        new
                        {
                            Id = 6,
                            Carbons = 6,
                            Fats = 6,
                            Name = "Product 6",
                            Proteins = 6,
                            Weight = 100
                        },
                        new
                        {
                            Id = 7,
                            Carbons = 7,
                            Fats = 7,
                            Name = "Product 7",
                            Proteins = 7,
                            Weight = 100
                        },
                        new
                        {
                            Id = 8,
                            Carbons = 8,
                            Fats = 8,
                            Name = "Product 8",
                            Proteins = 8,
                            Weight = 100
                        },
                        new
                        {
                            Id = 9,
                            Carbons = 9,
                            Fats = 9,
                            Name = "Product 9",
                            Proteins = 9,
                            Weight = 100
                        },
                        new
                        {
                            Id = 10,
                            Carbons = 10,
                            Fats = 10,
                            Name = "Product 10",
                            Proteins = 10,
                            Weight = 100
                        },
                        new
                        {
                            Id = 11,
                            Carbons = 11,
                            Fats = 11,
                            Name = "Product 11",
                            Proteins = 11,
                            Weight = 100
                        },
                        new
                        {
                            Id = 12,
                            Carbons = 12,
                            Fats = 12,
                            Name = "Product 12",
                            Proteins = 12,
                            Weight = 100
                        },
                        new
                        {
                            Id = 13,
                            Carbons = 13,
                            Fats = 13,
                            Name = "Product 13",
                            Proteins = 13,
                            Weight = 100
                        },
                        new
                        {
                            Id = 14,
                            Carbons = 14,
                            Fats = 14,
                            Name = "Product 14",
                            Proteins = 14,
                            Weight = 100
                        },
                        new
                        {
                            Id = 15,
                            Carbons = 15,
                            Fats = 15,
                            Name = "Product 15",
                            Proteins = 15,
                            Weight = 100
                        },
                        new
                        {
                            Id = 16,
                            Carbons = 16,
                            Fats = 16,
                            Name = "Product 16",
                            Proteins = 16,
                            Weight = 100
                        },
                        new
                        {
                            Id = 17,
                            Carbons = 17,
                            Fats = 17,
                            Name = "Product 17",
                            Proteins = 17,
                            Weight = 100
                        },
                        new
                        {
                            Id = 18,
                            Carbons = 18,
                            Fats = 18,
                            Name = "Product 18",
                            Proteins = 18,
                            Weight = 100
                        },
                        new
                        {
                            Id = 19,
                            Carbons = 19,
                            Fats = 19,
                            Name = "Product 19",
                            Proteins = 19,
                            Weight = 100
                        },
                        new
                        {
                            Id = 20,
                            Carbons = 20,
                            Fats = 20,
                            Name = "Product 20",
                            Proteins = 20,
                            Weight = 100
                        },
                        new
                        {
                            Id = 21,
                            Carbons = 21,
                            Fats = 21,
                            Name = "Product 21",
                            Proteins = 21,
                            Weight = 100
                        },
                        new
                        {
                            Id = 22,
                            Carbons = 22,
                            Fats = 22,
                            Name = "Product 22",
                            Proteins = 22,
                            Weight = 100
                        },
                        new
                        {
                            Id = 23,
                            Carbons = 23,
                            Fats = 23,
                            Name = "Product 23",
                            Proteins = 23,
                            Weight = 100
                        },
                        new
                        {
                            Id = 24,
                            Carbons = 24,
                            Fats = 24,
                            Name = "Product 24",
                            Proteins = 24,
                            Weight = 100
                        },
                        new
                        {
                            Id = 25,
                            Carbons = 25,
                            Fats = 25,
                            Name = "Product 25",
                            Proteins = 25,
                            Weight = 100
                        },
                        new
                        {
                            Id = 26,
                            Carbons = 26,
                            Fats = 26,
                            Name = "Product 26",
                            Proteins = 26,
                            Weight = 100
                        },
                        new
                        {
                            Id = 27,
                            Carbons = 27,
                            Fats = 27,
                            Name = "Product 27",
                            Proteins = 27,
                            Weight = 100
                        },
                        new
                        {
                            Id = 28,
                            Carbons = 28,
                            Fats = 28,
                            Name = "Product 28",
                            Proteins = 28,
                            Weight = 100
                        },
                        new
                        {
                            Id = 29,
                            Carbons = 29,
                            Fats = 29,
                            Name = "Product 29",
                            Proteins = 29,
                            Weight = 100
                        },
                        new
                        {
                            Id = 30,
                            Carbons = 30,
                            Fats = 30,
                            Name = "Product 30",
                            Proteins = 30,
                            Weight = 100
                        },
                        new
                        {
                            Id = 31,
                            Carbons = 31,
                            Fats = 31,
                            Name = "Product 31",
                            Proteins = 31,
                            Weight = 100
                        },
                        new
                        {
                            Id = 32,
                            Carbons = 32,
                            Fats = 32,
                            Name = "Product 32",
                            Proteins = 32,
                            Weight = 100
                        },
                        new
                        {
                            Id = 33,
                            Carbons = 33,
                            Fats = 33,
                            Name = "Product 33",
                            Proteins = 33,
                            Weight = 100
                        },
                        new
                        {
                            Id = 34,
                            Carbons = 34,
                            Fats = 34,
                            Name = "Product 34",
                            Proteins = 34,
                            Weight = 100
                        },
                        new
                        {
                            Id = 35,
                            Carbons = 35,
                            Fats = 35,
                            Name = "Product 35",
                            Proteins = 35,
                            Weight = 100
                        },
                        new
                        {
                            Id = 36,
                            Carbons = 36,
                            Fats = 36,
                            Name = "Product 36",
                            Proteins = 36,
                            Weight = 100
                        },
                        new
                        {
                            Id = 37,
                            Carbons = 37,
                            Fats = 37,
                            Name = "Product 37",
                            Proteins = 37,
                            Weight = 100
                        },
                        new
                        {
                            Id = 38,
                            Carbons = 38,
                            Fats = 38,
                            Name = "Product 38",
                            Proteins = 38,
                            Weight = 100
                        },
                        new
                        {
                            Id = 39,
                            Carbons = 39,
                            Fats = 39,
                            Name = "Product 39",
                            Proteins = 39,
                            Weight = 100
                        },
                        new
                        {
                            Id = 40,
                            Carbons = 40,
                            Fats = 40,
                            Name = "Product 40",
                            Proteins = 40,
                            Weight = 100
                        },
                        new
                        {
                            Id = 41,
                            Carbons = 41,
                            Fats = 41,
                            Name = "Product 41",
                            Proteins = 41,
                            Weight = 100
                        },
                        new
                        {
                            Id = 42,
                            Carbons = 42,
                            Fats = 42,
                            Name = "Product 42",
                            Proteins = 42,
                            Weight = 100
                        },
                        new
                        {
                            Id = 43,
                            Carbons = 43,
                            Fats = 43,
                            Name = "Product 43",
                            Proteins = 43,
                            Weight = 100
                        },
                        new
                        {
                            Id = 44,
                            Carbons = 44,
                            Fats = 44,
                            Name = "Product 44",
                            Proteins = 44,
                            Weight = 100
                        },
                        new
                        {
                            Id = 45,
                            Carbons = 45,
                            Fats = 45,
                            Name = "Product 45",
                            Proteins = 45,
                            Weight = 100
                        },
                        new
                        {
                            Id = 46,
                            Carbons = 46,
                            Fats = 46,
                            Name = "Product 46",
                            Proteins = 46,
                            Weight = 100
                        },
                        new
                        {
                            Id = 47,
                            Carbons = 47,
                            Fats = 47,
                            Name = "Product 47",
                            Proteins = 47,
                            Weight = 100
                        },
                        new
                        {
                            Id = 48,
                            Carbons = 48,
                            Fats = 48,
                            Name = "Product 48",
                            Proteins = 48,
                            Weight = 100
                        },
                        new
                        {
                            Id = 49,
                            Carbons = 49,
                            Fats = 49,
                            Name = "Product 49",
                            Proteins = 49,
                            Weight = 100
                        },
                        new
                        {
                            Id = 50,
                            Carbons = 50,
                            Fats = 50,
                            Name = "Product 50",
                            Proteins = 50,
                            Weight = 100
                        },
                        new
                        {
                            Id = 51,
                            Carbons = 51,
                            Fats = 51,
                            Name = "Product 51",
                            Proteins = 51,
                            Weight = 100
                        },
                        new
                        {
                            Id = 52,
                            Carbons = 52,
                            Fats = 52,
                            Name = "Product 52",
                            Proteins = 52,
                            Weight = 100
                        },
                        new
                        {
                            Id = 53,
                            Carbons = 53,
                            Fats = 53,
                            Name = "Product 53",
                            Proteins = 53,
                            Weight = 100
                        },
                        new
                        {
                            Id = 54,
                            Carbons = 54,
                            Fats = 54,
                            Name = "Product 54",
                            Proteins = 54,
                            Weight = 100
                        },
                        new
                        {
                            Id = 55,
                            Carbons = 55,
                            Fats = 55,
                            Name = "Product 55",
                            Proteins = 55,
                            Weight = 100
                        },
                        new
                        {
                            Id = 56,
                            Carbons = 56,
                            Fats = 56,
                            Name = "Product 56",
                            Proteins = 56,
                            Weight = 100
                        },
                        new
                        {
                            Id = 57,
                            Carbons = 57,
                            Fats = 57,
                            Name = "Product 57",
                            Proteins = 57,
                            Weight = 100
                        },
                        new
                        {
                            Id = 58,
                            Carbons = 58,
                            Fats = 58,
                            Name = "Product 58",
                            Proteins = 58,
                            Weight = 100
                        },
                        new
                        {
                            Id = 59,
                            Carbons = 59,
                            Fats = 59,
                            Name = "Product 59",
                            Proteins = 59,
                            Weight = 100
                        },
                        new
                        {
                            Id = 60,
                            Carbons = 60,
                            Fats = 60,
                            Name = "Product 60",
                            Proteins = 60,
                            Weight = 100
                        },
                        new
                        {
                            Id = 61,
                            Carbons = 61,
                            Fats = 61,
                            Name = "Product 61",
                            Proteins = 61,
                            Weight = 100
                        },
                        new
                        {
                            Id = 62,
                            Carbons = 62,
                            Fats = 62,
                            Name = "Product 62",
                            Proteins = 62,
                            Weight = 100
                        },
                        new
                        {
                            Id = 63,
                            Carbons = 63,
                            Fats = 63,
                            Name = "Product 63",
                            Proteins = 63,
                            Weight = 100
                        },
                        new
                        {
                            Id = 64,
                            Carbons = 64,
                            Fats = 64,
                            Name = "Product 64",
                            Proteins = 64,
                            Weight = 100
                        },
                        new
                        {
                            Id = 65,
                            Carbons = 65,
                            Fats = 65,
                            Name = "Product 65",
                            Proteins = 65,
                            Weight = 100
                        },
                        new
                        {
                            Id = 66,
                            Carbons = 66,
                            Fats = 66,
                            Name = "Product 66",
                            Proteins = 66,
                            Weight = 100
                        },
                        new
                        {
                            Id = 67,
                            Carbons = 67,
                            Fats = 67,
                            Name = "Product 67",
                            Proteins = 67,
                            Weight = 100
                        },
                        new
                        {
                            Id = 68,
                            Carbons = 68,
                            Fats = 68,
                            Name = "Product 68",
                            Proteins = 68,
                            Weight = 100
                        },
                        new
                        {
                            Id = 69,
                            Carbons = 69,
                            Fats = 69,
                            Name = "Product 69",
                            Proteins = 69,
                            Weight = 100
                        },
                        new
                        {
                            Id = 70,
                            Carbons = 70,
                            Fats = 70,
                            Name = "Product 70",
                            Proteins = 70,
                            Weight = 100
                        },
                        new
                        {
                            Id = 71,
                            Carbons = 71,
                            Fats = 71,
                            Name = "Product 71",
                            Proteins = 71,
                            Weight = 100
                        },
                        new
                        {
                            Id = 72,
                            Carbons = 72,
                            Fats = 72,
                            Name = "Product 72",
                            Proteins = 72,
                            Weight = 100
                        },
                        new
                        {
                            Id = 73,
                            Carbons = 73,
                            Fats = 73,
                            Name = "Product 73",
                            Proteins = 73,
                            Weight = 100
                        },
                        new
                        {
                            Id = 74,
                            Carbons = 74,
                            Fats = 74,
                            Name = "Product 74",
                            Proteins = 74,
                            Weight = 100
                        },
                        new
                        {
                            Id = 75,
                            Carbons = 75,
                            Fats = 75,
                            Name = "Product 75",
                            Proteins = 75,
                            Weight = 100
                        },
                        new
                        {
                            Id = 76,
                            Carbons = 76,
                            Fats = 76,
                            Name = "Product 76",
                            Proteins = 76,
                            Weight = 100
                        },
                        new
                        {
                            Id = 77,
                            Carbons = 77,
                            Fats = 77,
                            Name = "Product 77",
                            Proteins = 77,
                            Weight = 100
                        },
                        new
                        {
                            Id = 78,
                            Carbons = 78,
                            Fats = 78,
                            Name = "Product 78",
                            Proteins = 78,
                            Weight = 100
                        },
                        new
                        {
                            Id = 79,
                            Carbons = 79,
                            Fats = 79,
                            Name = "Product 79",
                            Proteins = 79,
                            Weight = 100
                        },
                        new
                        {
                            Id = 80,
                            Carbons = 80,
                            Fats = 80,
                            Name = "Product 80",
                            Proteins = 80,
                            Weight = 100
                        },
                        new
                        {
                            Id = 81,
                            Carbons = 81,
                            Fats = 81,
                            Name = "Product 81",
                            Proteins = 81,
                            Weight = 100
                        },
                        new
                        {
                            Id = 82,
                            Carbons = 82,
                            Fats = 82,
                            Name = "Product 82",
                            Proteins = 82,
                            Weight = 100
                        },
                        new
                        {
                            Id = 83,
                            Carbons = 83,
                            Fats = 83,
                            Name = "Product 83",
                            Proteins = 83,
                            Weight = 100
                        },
                        new
                        {
                            Id = 84,
                            Carbons = 84,
                            Fats = 84,
                            Name = "Product 84",
                            Proteins = 84,
                            Weight = 100
                        },
                        new
                        {
                            Id = 85,
                            Carbons = 85,
                            Fats = 85,
                            Name = "Product 85",
                            Proteins = 85,
                            Weight = 100
                        },
                        new
                        {
                            Id = 86,
                            Carbons = 86,
                            Fats = 86,
                            Name = "Product 86",
                            Proteins = 86,
                            Weight = 100
                        },
                        new
                        {
                            Id = 87,
                            Carbons = 87,
                            Fats = 87,
                            Name = "Product 87",
                            Proteins = 87,
                            Weight = 100
                        },
                        new
                        {
                            Id = 88,
                            Carbons = 88,
                            Fats = 88,
                            Name = "Product 88",
                            Proteins = 88,
                            Weight = 100
                        },
                        new
                        {
                            Id = 89,
                            Carbons = 89,
                            Fats = 89,
                            Name = "Product 89",
                            Proteins = 89,
                            Weight = 100
                        },
                        new
                        {
                            Id = 90,
                            Carbons = 90,
                            Fats = 90,
                            Name = "Product 90",
                            Proteins = 90,
                            Weight = 100
                        },
                        new
                        {
                            Id = 91,
                            Carbons = 91,
                            Fats = 91,
                            Name = "Product 91",
                            Proteins = 91,
                            Weight = 100
                        },
                        new
                        {
                            Id = 92,
                            Carbons = 92,
                            Fats = 92,
                            Name = "Product 92",
                            Proteins = 92,
                            Weight = 100
                        },
                        new
                        {
                            Id = 93,
                            Carbons = 93,
                            Fats = 93,
                            Name = "Product 93",
                            Proteins = 93,
                            Weight = 100
                        },
                        new
                        {
                            Id = 94,
                            Carbons = 94,
                            Fats = 94,
                            Name = "Product 94",
                            Proteins = 94,
                            Weight = 100
                        },
                        new
                        {
                            Id = 95,
                            Carbons = 95,
                            Fats = 95,
                            Name = "Product 95",
                            Proteins = 95,
                            Weight = 100
                        },
                        new
                        {
                            Id = 96,
                            Carbons = 96,
                            Fats = 96,
                            Name = "Product 96",
                            Proteins = 96,
                            Weight = 100
                        },
                        new
                        {
                            Id = 97,
                            Carbons = 97,
                            Fats = 97,
                            Name = "Product 97",
                            Proteins = 97,
                            Weight = 100
                        },
                        new
                        {
                            Id = 98,
                            Carbons = 98,
                            Fats = 98,
                            Name = "Product 98",
                            Proteins = 98,
                            Weight = 100
                        },
                        new
                        {
                            Id = 99,
                            Carbons = 99,
                            Fats = 99,
                            Name = "Product 99",
                            Proteins = 99,
                            Weight = 100
                        },
                        new
                        {
                            Id = 100,
                            Carbons = 100,
                            Fats = 100,
                            Name = "Product 100",
                            Proteins = 100,
                            Weight = 100
                        });
                });

            modelBuilder.Entity("MakeYourDiet.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1730),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1732),
                            Password = "password",
                            UserName = "User 1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1754),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1755),
                            Password = "password",
                            UserName = "User 2"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1756),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1756),
                            Password = "password",
                            UserName = "User 3"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1757),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1757),
                            Password = "password",
                            UserName = "User 4"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1758),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1758),
                            Password = "password",
                            UserName = "User 5"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1759),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1760),
                            Password = "password",
                            UserName = "User 6"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1760),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1761),
                            Password = "password",
                            UserName = "User 7"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1762),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1762),
                            Password = "password",
                            UserName = "User 8"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1763),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1763),
                            Password = "password",
                            UserName = "User 9"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1764),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1764),
                            Password = "password",
                            UserName = "User 10"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1765),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1766),
                            Password = "password",
                            UserName = "User 11"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1766),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1767),
                            Password = "password",
                            UserName = "User 12"
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1767),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1768),
                            Password = "password",
                            UserName = "User 13"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1768),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1769),
                            Password = "password",
                            UserName = "User 14"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1770),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1770),
                            Password = "password",
                            UserName = "User 15"
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1771),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1771),
                            Password = "password",
                            UserName = "User 16"
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1772),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1772),
                            Password = "password",
                            UserName = "User 17"
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1773),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1773),
                            Password = "password",
                            UserName = "User 18"
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1774),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1774),
                            Password = "password",
                            UserName = "User 19"
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1775),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1775),
                            Password = "password",
                            UserName = "User 20"
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1776),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1776),
                            Password = "password",
                            UserName = "User 21"
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1777),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1777),
                            Password = "password",
                            UserName = "User 22"
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1778),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1778),
                            Password = "password",
                            UserName = "User 23"
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1779),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1779),
                            Password = "password",
                            UserName = "User 24"
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1780),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1780),
                            Password = "password",
                            UserName = "User 25"
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1781),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1781),
                            Password = "password",
                            UserName = "User 26"
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1782),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1782),
                            Password = "password",
                            UserName = "User 27"
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1783),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1783),
                            Password = "password",
                            UserName = "User 28"
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1784),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1784),
                            Password = "password",
                            UserName = "User 29"
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1785),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1785),
                            Password = "password",
                            UserName = "User 30"
                        },
                        new
                        {
                            Id = 31,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1786),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1786),
                            Password = "password",
                            UserName = "User 31"
                        },
                        new
                        {
                            Id = 32,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1787),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1787),
                            Password = "password",
                            UserName = "User 32"
                        },
                        new
                        {
                            Id = 33,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1788),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1788),
                            Password = "password",
                            UserName = "User 33"
                        },
                        new
                        {
                            Id = 34,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1812),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1812),
                            Password = "password",
                            UserName = "User 34"
                        },
                        new
                        {
                            Id = 35,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1813),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1814),
                            Password = "password",
                            UserName = "User 35"
                        },
                        new
                        {
                            Id = 36,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1814),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1815),
                            Password = "password",
                            UserName = "User 36"
                        },
                        new
                        {
                            Id = 37,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1816),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1816),
                            Password = "password",
                            UserName = "User 37"
                        },
                        new
                        {
                            Id = 38,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1817),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1817),
                            Password = "password",
                            UserName = "User 38"
                        },
                        new
                        {
                            Id = 39,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1818),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1818),
                            Password = "password",
                            UserName = "User 39"
                        },
                        new
                        {
                            Id = 40,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1819),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1819),
                            Password = "password",
                            UserName = "User 40"
                        },
                        new
                        {
                            Id = 41,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1820),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1820),
                            Password = "password",
                            UserName = "User 41"
                        },
                        new
                        {
                            Id = 42,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1821),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1821),
                            Password = "password",
                            UserName = "User 42"
                        },
                        new
                        {
                            Id = 43,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1822),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1822),
                            Password = "password",
                            UserName = "User 43"
                        },
                        new
                        {
                            Id = 44,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1823),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1823),
                            Password = "password",
                            UserName = "User 44"
                        },
                        new
                        {
                            Id = 45,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1823),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1824),
                            Password = "password",
                            UserName = "User 45"
                        },
                        new
                        {
                            Id = 46,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1824),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1825),
                            Password = "password",
                            UserName = "User 46"
                        },
                        new
                        {
                            Id = 47,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1825),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1826),
                            Password = "password",
                            UserName = "User 47"
                        },
                        new
                        {
                            Id = 48,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1826),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1827),
                            Password = "password",
                            UserName = "User 48"
                        },
                        new
                        {
                            Id = 49,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1827),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1828),
                            Password = "password",
                            UserName = "User 49"
                        },
                        new
                        {
                            Id = 50,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1828),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1828),
                            Password = "password",
                            UserName = "User 50"
                        },
                        new
                        {
                            Id = 51,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1829),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1829),
                            Password = "password",
                            UserName = "User 51"
                        },
                        new
                        {
                            Id = 52,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1830),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1830),
                            Password = "password",
                            UserName = "User 52"
                        },
                        new
                        {
                            Id = 53,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1831),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1831),
                            Password = "password",
                            UserName = "User 53"
                        },
                        new
                        {
                            Id = 54,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1832),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1832),
                            Password = "password",
                            UserName = "User 54"
                        },
                        new
                        {
                            Id = 55,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1833),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1833),
                            Password = "password",
                            UserName = "User 55"
                        },
                        new
                        {
                            Id = 56,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1834),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1834),
                            Password = "password",
                            UserName = "User 56"
                        },
                        new
                        {
                            Id = 57,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1835),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1835),
                            Password = "password",
                            UserName = "User 57"
                        },
                        new
                        {
                            Id = 58,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1836),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1836),
                            Password = "password",
                            UserName = "User 58"
                        },
                        new
                        {
                            Id = 59,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1836),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1837),
                            Password = "password",
                            UserName = "User 59"
                        },
                        new
                        {
                            Id = 60,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1837),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1838),
                            Password = "password",
                            UserName = "User 60"
                        },
                        new
                        {
                            Id = 61,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1838),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1839),
                            Password = "password",
                            UserName = "User 61"
                        },
                        new
                        {
                            Id = 62,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1839),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1840),
                            Password = "password",
                            UserName = "User 62"
                        },
                        new
                        {
                            Id = 63,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1840),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1840),
                            Password = "password",
                            UserName = "User 63"
                        },
                        new
                        {
                            Id = 64,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1841),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1841),
                            Password = "password",
                            UserName = "User 64"
                        },
                        new
                        {
                            Id = 65,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1842),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1842),
                            Password = "password",
                            UserName = "User 65"
                        },
                        new
                        {
                            Id = 66,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1843),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1843),
                            Password = "password",
                            UserName = "User 66"
                        },
                        new
                        {
                            Id = 67,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1844),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1844),
                            Password = "password",
                            UserName = "User 67"
                        },
                        new
                        {
                            Id = 68,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1845),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1845),
                            Password = "password",
                            UserName = "User 68"
                        },
                        new
                        {
                            Id = 69,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1846),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1846),
                            Password = "password",
                            UserName = "User 69"
                        },
                        new
                        {
                            Id = 70,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1847),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1847),
                            Password = "password",
                            UserName = "User 70"
                        },
                        new
                        {
                            Id = 71,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1848),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1848),
                            Password = "password",
                            UserName = "User 71"
                        },
                        new
                        {
                            Id = 72,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1848),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1849),
                            Password = "password",
                            UserName = "User 72"
                        },
                        new
                        {
                            Id = 73,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1849),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1850),
                            Password = "password",
                            UserName = "User 73"
                        },
                        new
                        {
                            Id = 74,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1850),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1851),
                            Password = "password",
                            UserName = "User 74"
                        },
                        new
                        {
                            Id = 75,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1851),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1851),
                            Password = "password",
                            UserName = "User 75"
                        },
                        new
                        {
                            Id = 76,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1852),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1852),
                            Password = "password",
                            UserName = "User 76"
                        },
                        new
                        {
                            Id = 77,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1853),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1853),
                            Password = "password",
                            UserName = "User 77"
                        },
                        new
                        {
                            Id = 78,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1854),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1854),
                            Password = "password",
                            UserName = "User 78"
                        },
                        new
                        {
                            Id = 79,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1855),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1855),
                            Password = "password",
                            UserName = "User 79"
                        },
                        new
                        {
                            Id = 80,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1856),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1856),
                            Password = "password",
                            UserName = "User 80"
                        },
                        new
                        {
                            Id = 81,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1857),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1857),
                            Password = "password",
                            UserName = "User 81"
                        },
                        new
                        {
                            Id = 82,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1858),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1858),
                            Password = "password",
                            UserName = "User 82"
                        },
                        new
                        {
                            Id = 83,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1859),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1859),
                            Password = "password",
                            UserName = "User 83"
                        },
                        new
                        {
                            Id = 84,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1860),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1860),
                            Password = "password",
                            UserName = "User 84"
                        },
                        new
                        {
                            Id = 85,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1860),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1861),
                            Password = "password",
                            UserName = "User 85"
                        },
                        new
                        {
                            Id = 86,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1861),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1862),
                            Password = "password",
                            UserName = "User 86"
                        },
                        new
                        {
                            Id = 87,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1862),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1863),
                            Password = "password",
                            UserName = "User 87"
                        },
                        new
                        {
                            Id = 88,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1863),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1863),
                            Password = "password",
                            UserName = "User 88"
                        },
                        new
                        {
                            Id = 89,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1864),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1864),
                            Password = "password",
                            UserName = "User 89"
                        },
                        new
                        {
                            Id = 90,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1865),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1865),
                            Password = "password",
                            UserName = "User 90"
                        },
                        new
                        {
                            Id = 91,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1866),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1866),
                            Password = "password",
                            UserName = "User 91"
                        },
                        new
                        {
                            Id = 92,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1867),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1867),
                            Password = "password",
                            UserName = "User 92"
                        },
                        new
                        {
                            Id = 93,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1868),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1868),
                            Password = "password",
                            UserName = "User 93"
                        },
                        new
                        {
                            Id = 94,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1869),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1869),
                            Password = "password",
                            UserName = "User 94"
                        },
                        new
                        {
                            Id = 95,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1870),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1870),
                            Password = "password",
                            UserName = "User 95"
                        },
                        new
                        {
                            Id = 96,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1871),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1871),
                            Password = "password",
                            UserName = "User 96"
                        },
                        new
                        {
                            Id = 97,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1871),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1872),
                            Password = "password",
                            UserName = "User 97"
                        },
                        new
                        {
                            Id = 98,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1872),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1873),
                            Password = "password",
                            UserName = "User 98"
                        },
                        new
                        {
                            Id = 99,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1873),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1874),
                            Password = "password",
                            UserName = "User 99"
                        },
                        new
                        {
                            Id = 100,
                            Created = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1874),
                            Gender = "male",
                            LastActive = new DateTime(2023, 8, 27, 17, 12, 32, 423, DateTimeKind.Utc).AddTicks(1874),
                            Password = "password",
                            UserName = "User 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
